name: run ws.py

on:
  schedule:
    - cron: '* 3 * * *'

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:

      - name: check conteudo do repositorio
        uses: actions/checkout@v3

      - name: instalar o python
        uses: actions/setup-python@v4

      - name: instalar os pacotes do requirements.txt
        run: python -m pip install pip install -r requirements.txt

      - name: executar arquivo scrapping
        env:
          TOKEN_01: ${{ secrets.TOKEN_01 }}
          TOKEN_02: ${{ secrets.TOKEN_02 }}
        run: python ws.py
