name: ws01

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install requirements
        run: python -m pip install pip install -r requirements.txt
      - name: Run a Python script
        env:
          TOKEN_01: ${{ secrets.TOKEN_01 }}
          TOKEN_02: ${{ secrets.TOKEN_02 }}
        run: python ws.py
